control 'packages-1' do
  impact 0.8
  title 'Ensure all repos have gpg checking enabled'
  desc '
    All yum repositories should have package checking enabled.
  '

  tag 'packages'
  ref 'Compliance: Host Access', url: 'https://wiki.example.com/security/compliance/ops/Software+Security'

  # We check that the repo file has the comment yum_repository adds to repo
  # files.  Each repo gets its own file that way.  We're then able to check
  # that gpgpcheck is enabled on all of them.
  files = command('ls /etc/yum.repos.d/*.repo').stdout.strip.lines
  files.each do |f|
    describe file(f.strip) do
      its('content') { should match /# This file was generated by Chef/ }
      its('content') { should match /gpgcheck=1/ }
    end
  end
end

