---
driver:
  name: vagrant
  cachier: true
  require_chef_omnibus: 13.0.118
  customize:
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - role[<%= ENV['ROLE'] != nil ? ENV[ROLE] : 'base' %>]
    attributes:
      ntp:
        servers:
          - pool.ntp.org
      threatstack:
        deploy_key: <%= ENV['TS_DEPLOY_KEY'] != nil ? ENV['TS_DEPLOY_KEY'] : 'ts_deploy_key' %>
        feature_plan: <%= ENV['TS_FEATURE_PLAN'] != nil ? ENV['TS_FEATURE_PLAN'] : 'monitor' %>
        version: <%= ENV['TS_PACKAGE_VERSION'] %>
        configure_agent: <%= ENV['TS_CONFIG_AGENT'] == '1' ? true : false %>

