---
driver:
  name: vagrant
  cachier: true
  require_chef_omnibus: 13.0.118
  customize:
    cpus: 2

provisioner:
  name: chef_zero

verifier:
  name: inspec
  inspec_tests:
    - name: base
      path: cookbooks/base/test/integration/inspec
    <% if ENV['ROLE'] != nil %>
    - name: site-nginx
      path: cookbooks/site-nginx/test/integration/inspec
    - name: svc-threatstack-to-s3
      path: cookbooks/svc-threatstack-to-s3/test/integration/inspec
    <% end %>
  attrs:
    - cookbooks/base/test/integration/inspec/attributes/vagrant.yml
    - cookbooks/base/test/integration/inspec/attributes/default.yml
    - cookbooks/svc-threatstack-to-s3/test/integration/inspec/attributes/default.yml

platforms:
  - name: centos-7.3

suites:
  - name: <%= ENV['ROLE'] != nil ? ENV['ROLE'] : 'base' %>
    run_list:
      - role[<%= ENV['ROLE'] != nil ? ENV['ROLE'] : 'base' %>]
    attributes:
      ntp:
        servers:
          - pool.ntp.org
      threatstack:
        deploy_key: <%= ENV['TS_DEPLOY_KEY'] != nil ? ENV['TS_DEPLOY_KEY'] : 'ts_deploy_key' %>
        feature_plan: <%= ENV['TS_FEATURE_PLAN'] != nil ? ENV['TS_FEATURE_PLAN'] : 'monitor' %>
        version: <%= ENV['TS_PACKAGE_VERSION'] %>
        configure_agent: <%= ENV['TS_CONFIG_AGENT'] == '1' ? true : false %>
        cloudsight_service_action: <%= ENV['TS_SERVICE_ACTION'] != nil ? ENV['TS_SERVICE_ACTION'] : 'enable' %>

